POST http://10.243.10.205:32080/detection/decision/execute
Accept: application/json

{
  "message": {
    "request": {
      "messageClassificationName": "SAMPLEmcns",
      "restResponseFlg": 0,
      "schemaName": "online fraud"
    },
    "solution": {
      "activityType": "NM",
      "authenticationType": "NA",
      "channelType": "DM",
      "customerType": "BU",
      "originationType": "CS",
      "source": "ONEPAY",
      "messageDtTm": "2025-08-02T10:15:10.702Z"
    },
    "authentication": {
      "decision": "A"
    },
    "customer": {
      "identifier": "r2_028"
    },
    "payment": {
      "amount": "2000"
    },
    "device": {
      "macAddress": ""
    }
  }
}

POST http://10.243.10.205:32080/detection/decision/execute
Accept: application/json

{
  "message": {
    "request": {
      "messageClassificationName": "SAMPLEmcns",
      "restResponseFlg": 0,
      "schemaName": "online fraud"
    },
    "solution": {
      "activityType": "NM",
      "authenticationType": "NA",
      "channelType": "DM",
      "customerType": "BU",
      "originationType": "CS",
      "source": "ONEPAY",
      "messageDtTm": "2025-08-02T10:20:10.702Z"
    },
    "authentication": {
      "decision": "A"
    },
    "customer": {
      "identifier": "r2_025"
    },
    "payment": {
      "amount": "2000"
    },
    "device": {
      "macAddress": ""
    }
  }
}