         queue_id         |         queue_nm         | queue_desc |      domain_id      |     triage_type_id     | default_queue_flg | queue_service_priority_val | queue_service_sort_field_order | queue_service_enabled_flg | alert_max_duration_in_q_val | queue_routing_enabled_flg | queue_routing_priority_val | queue_routing_rule_val | queue_sticky_flg | opt_lock_version_no |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | group_id | auto_disposition_id | queue_reactivation_rule_val | queue_reactivation_enabled_flg
--------------------------+--------------------------+------------+---------------------+------------------------+-------------------+----------------------------+--------------------------------+---------------------------+-----------------------------+---------------------------+----------------------------+------------------------+------------------+---------------------+-------------------------------+---------------+-------------------------------+----------------+----------+---------------------+-----------------------------+--------------------------------
 high_corporate_queue     | High Corporate Queue     |            | online_fraud_domain | corporate_triage_type  | f                 |                          5 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          5 |                        | f                |                  90 | 2025-05-08 11:06:05.619586+00 | fraudsvc      | 2025-05-13 10:09:13.889841+00 | fraudsvc       |          |                     |                             | t
 high_individual_queue    | High Individual Queue    |            | online_fraud_domain | individual_triage_type | f                 |                          2 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          2 |                        | f                |                  90 | 2025-05-08 11:01:31.695844+00 | fraudsvc      | 2025-05-13 10:09:13.899229+00 | fraudsvc       |          |                     |                             | t
 low_corporate_queue      | Low Corporate Queue      |            | online_fraud_domain | corporate_triage_type  | f                 |                          6 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          6 |                        | f                |                  90 | 2025-05-08 11:06:05.633083+00 | fraudsvc      | 2025-05-13 10:09:13.908608+00 | fraudsvc       |          |                     |                             | t
 manager_corporate_queue  | Manager Corporate Queue  |            | online_fraud_domain | corporate_triage_type  | f                 |                          4 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          4 |                        | f                |                  90 | 2025-05-08 11:06:05.645544+00 | fraudsvc      | 2025-05-13 10:09:13.927335+00 | fraudsvc       |          |                     |                             | t
 manager_individual_queue | Manager Individual Queue |            | online_fraud_domain | individual_triage_type | f                 |                          1 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          1 |                        | f                |                  90 | 2025-05-08 11:01:31.738083+00 | fraudsvc      | 2025-05-13 10:09:13.936805+00 | fraudsvc       |          |                     |                             | t
 low_individual_queue     | Low Individual Queue     |            | online_fraud_domain | individual_triage_type | t                 |                          3 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          3 |                        | f                |                  91 | 2025-05-08 11:01:31.722306+00 | fraudsvc      | 2025-05-13 10:35:43.278505+00 | fraudsvc       |          |                     |                             | t




         queue_id         |         queue_nm         | queue_desc |      domain_id      |     triage_type_id     | default_queue_flg | queue_service_priority_val | queue_service_sort_field_order | queue_service_enabled_flg | alert_max_duration_in_q_val | queue_routing_enabled_flg | queue_routing_priority_val | queue_routing_rule_val | queue_sticky_flg | opt_lock_version_no |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | group_id | auto_disposition_id | queue_reactivation_rule_val | queue_reactivation_enabled_flg
--------------------------+--------------------------+------------+---------------------+------------------------+-------------------+----------------------------+--------------------------------+---------------------------+-----------------------------+---------------------------+----------------------------+------------------------+------------------+---------------------+-------------------------------+---------------+-------------------------------+----------------+----------+---------------------+-----------------------------+--------------------------------
 high_corporate_queue     | High Corporate Queue     |            | online_fraud_domain | corporate_triage_type  | f                 |                          5 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          5 |                        | f                |                  90 | 2025-05-08 11:06:05.619586+00 | fraudsvc      | 2025-05-13 10:09:13.889841+00 | fraudsvc       |          |                     |                             | t
 high_individual_queue    | High Individual Queue    |            | online_fraud_domain | individual_triage_type | f                 |                          2 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          2 |                        | f                |                  90 | 2025-05-08 11:01:31.695844+00 | fraudsvc      | 2025-05-13 10:09:13.899229+00 | fraudsvc       |          |                     |                             | t
 manager_corporate_queue  | Manager Corporate Queue  |            | online_fraud_domain | corporate_triage_type  | f                 |                          4 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          4 |                        | f                |                  90 | 2025-05-08 11:06:05.645544+00 | fraudsvc      | 2025-05-13 10:09:13.927335+00 | fraudsvc       |          |                     |                             | t
 manager_individual_queue | Manager Individual Queue |            | online_fraud_domain | individual_triage_type | f                 |                          1 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          1 |                        | f                |                  90 | 2025-05-08 11:01:31.738083+00 | fraudsvc      | 2025-05-13 10:09:13.936805+00 | fraudsvc       |          |                     |                             | t
 low_individual_queue     | Low Individual Queue     |            | online_fraud_domain | individual_triage_type | t                 |                          3 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          3 |                        | f                |                  91 | 2025-05-08 11:01:31.722306+00 | fraudsvc      | 2025-05-13 10:35:43.278505+00 | fraudsvc       |          |                     |                             | t
 low_corporate_queue      | Low Corporate Queue      |            | online_fraud_domain | corporate_triage_type  | t                 |                          6 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          6 |                        | f                |                  90 | 2025-05-08 11:06:05.633083+00 | fraudsvc      | 2025-05-13 10:09:13.908608+00 | fraudsvc       |          |                     |                             | t



    alert_id     | actionable_entity_id | actionable_entity_type_id | actionable_entity_label_nm | parent_entity_id | parent_entity_type_id | contact_entity_id | contact_entity_type_id | score_val | alert_origin_cd |           alert_origin_id            | status_cd | productivity_rating_cd | checkout_user_id | checkout_dttm | checkout_service_type_cd | disposition_dttm | auto_activate_dttm | auto_close_dttm |   auto_close_in_queue_dttm    | opt_lock_version_no |      domain_id      |      queue_id       | alert_type_cd | alert_trigger_txt |                                                                                         enrichment_json_doc                                                                                         |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | disposition_reason_cd
-----------------+----------------------+---------------------------+----------------------------+------------------+-----------------------+-------------------+------------------------+-----------+-----------------+--------------------------------------+-----------+------------------------+------------------+---------------+--------------------------+------------------+--------------------+-----------------+-------------------------------+---------------------+---------------------+---------------------+---------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+---------------+-------------------------------+----------------+-----------------------
 907741815693373 | test05               | sfd_customer              | test05                     | test05           | sfd_customer          | test05            | sfd_customer           |         0 | KAFKA           | f4e9e8b5-7763-4d14-921e-a553b3f7ddb7 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:30:31.902282+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:30:31.903125+00 | sas.alerts    | 2025-05-13 12:30:31.903125+00 | sas.alerts     |
 025629746001441 | test06               | sfd_customer              | test06                     | test06           | sfd_customer          | test06            | sfd_customer           |         0 | KAFKA           | a391052d-8f77-4937-96cc-82a578a0be33 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:38:11.163237+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:38:11.163521+00 | sas.alerts    | 2025-05-13 12:38:11.163521+00 | sas.alerts     |





         queue_id         |         queue_nm         | queue_desc |      domain_id      |     triage_type_id     | default_queue_flg | queue_service_priority_val | queue_service_sort_field_order | queue_service_enabled_flg | alert_max_duration_in_q_val | queue_routing_enabled_flg | queue_routing_priority_val | queue_routing_rule_val | queue_sticky_flg | opt_lock_version_no |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | group_id | auto_disposition_id | queue_reactivation_rule_val | queue_reactivation_enabled_flg
--------------------------+--------------------------+------------+---------------------+------------------------+-------------------+----------------------------+--------------------------------+---------------------------+-----------------------------+---------------------------+----------------------------+------------------------+------------------+---------------------+-------------------------------+---------------+-------------------------------+----------------+----------+---------------------+-----------------------------+--------------------------------
 high_corporate_queue     | High Corporate Queue     |            | online_fraud_domain | corporate_triage_type  | f                 |                          5 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          5 |                        | f                |                  90 | 2025-05-08 11:06:05.619586+00 | fraudsvc      | 2025-05-13 10:09:13.889841+00 | fraudsvc       |          |                     |                             | t
 high_individual_queue    | High Individual Queue    |            | online_fraud_domain | individual_triage_type | f                 |                          2 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          2 |                        | f                |                  90 | 2025-05-08 11:01:31.695844+00 | fraudsvc      | 2025-05-13 10:09:13.899229+00 | fraudsvc       |          |                     |                             | t
 manager_corporate_queue  | Manager Corporate Queue  |            | online_fraud_domain | corporate_triage_type  | f                 |                          4 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          4 |                        | f                |                  90 | 2025-05-08 11:06:05.645544+00 | fraudsvc      | 2025-05-13 10:09:13.927335+00 | fraudsvc       |          |                     |                             | t
 manager_individual_queue | Manager Individual Queue |            | online_fraud_domain | individual_triage_type | f                 |                          1 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          1 |                        | f                |                  90 | 2025-05-08 11:01:31.738083+00 | fraudsvc      | 2025-05-13 10:09:13.936805+00 | fraudsvc       |          |                     |                             | t
 low_individual_queue     | Low Individual Queue     |            | online_fraud_domain | individual_triage_type | t                 |                          3 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          3 |                        | f                |                  91 | 2025-05-08 11:01:31.722306+00 | fraudsvc      | 2025-05-13 10:35:43.278505+00 | fraudsvc       |          |                     |                             | t
 low_corporate_queue      | Low Corporate Queue      |            | online_fraud_domain | corporate_triage_type  | f                 |                          6 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          6 |                        | f                |                  90 | 2025-05-08 11:06:05.633083+00 | fraudsvc      | 2025-05-13 10:09:13.908608+00 | fraudsvc       |          |                     |                             | t
(6 rows)



    alert_id     | actionable_entity_id | actionable_entity_type_id | actionable_entity_label_nm | parent_entity_id | parent_entity_type_id | contact_entity_id | contact_entity_type_id | score_val | alert_origin_cd |           alert_origin_id            | status_cd | productivity_rating_cd | checkout_user_id | checkout_dttm | checkout_service_type_cd | disposition_dttm | auto_activate_dttm | auto_close_dttm |   auto_close_in_queue_dttm    | opt_lock_version_no |      domain_id      |      queue_id       | alert_type_cd | alert_trigger_txt |                                                                                         enrichment_json_doc                                                                                         |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | disposition_reason_cd
-----------------+----------------------+---------------------------+----------------------------+------------------+-----------------------+-------------------+------------------------+-----------+-----------------+--------------------------------------+-----------+------------------------+------------------+---------------+--------------------------+------------------+--------------------+-----------------+-------------------------------+---------------------+---------------------+---------------------+---------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+---------------+-------------------------------+----------------+-----------------------
 907741815693373 | test05               | sfd_customer              | test05                     | test05           | sfd_customer          | test05            | sfd_customer           |         0 | KAFKA           | f4e9e8b5-7763-4d14-921e-a553b3f7ddb7 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:30:31.902282+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:30:31.903125+00 | sas.alerts    | 2025-05-13 12:30:31.903125+00 | sas.alerts     |
 025629746001441 | test06               | sfd_customer              | test06                     | test06           | sfd_customer          | test06            | sfd_customer           |         0 | KAFKA           | a391052d-8f77-4937-96cc-82a578a0be33 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:38:11.163237+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:38:11.163521+00 | sas.alerts    | 2025-05-13 12:38:11.163521+00 | sas.alerts     |
 858321391877415 | r2_025               | sfd_customer              | r2_025                     | r2_025           | sfd_customer          | r2_025            | sfd_customer           |         0 | KAFKA           | d9e9a7d1-9022-4a7f-973c-7cabbe40c00a | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:03:39.499126+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:03:39.499401+00 | sas.alerts    | 2025-05-13 13:03:39.499401+00 | sas.alerts     |
(3 rows)


         queue_id         |         queue_nm         | queue_desc |      domain_id      |     triage_type_id     | default_queue_flg | queue_service_priority_val | queue_service_sort_field_order | queue_service_enabled_flg | alert_max_duration_in_q_val | queue_routing_enabled_flg | queue_routing_priority_val | queue_routing_rule_val | queue_sticky_flg | opt_lock_version_no |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | group_id | auto_disposition_id | queue_reactivation_rule_val | queue_reactivation_enabled_flg
--------------------------+--------------------------+------------+---------------------+------------------------+-------------------+----------------------------+--------------------------------+---------------------------+-----------------------------+---------------------------+----------------------------+------------------------+------------------+---------------------+-------------------------------+---------------+-------------------------------+----------------+----------+---------------------+-----------------------------+--------------------------------
 high_corporate_queue     | High Corporate Queue     |            | online_fraud_domain | corporate_triage_type  | f                 |                          5 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          5 |                        | f                |                  90 | 2025-05-08 11:06:05.619586+00 | fraudsvc      | 2025-05-13 10:09:13.889841+00 | fraudsvc       |          |                     |                             | t
 high_individual_queue    | High Individual Queue    |            | online_fraud_domain | individual_triage_type | f                 |                          2 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          2 |                        | f                |                  90 | 2025-05-08 11:01:31.695844+00 | fraudsvc      | 2025-05-13 10:09:13.899229+00 | fraudsvc       |          |                     |                             | t
 manager_corporate_queue  | Manager Corporate Queue  |            | online_fraud_domain | corporate_triage_type  | f                 |                          4 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          4 |                        | f                |                  90 | 2025-05-08 11:06:05.645544+00 | fraudsvc      | 2025-05-13 10:09:13.927335+00 | fraudsvc       |          |                     |                             | t
 manager_individual_queue | Manager Individual Queue |            | online_fraud_domain | individual_triage_type | f                 |                          1 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          1 |                        | f                |                  90 | 2025-05-08 11:01:31.738083+00 | fraudsvc      | 2025-05-13 10:09:13.936805+00 | fraudsvc       |          |                     |                             | t
 low_individual_queue     | Low Individual Queue     |            | online_fraud_domain | individual_triage_type | t                 |                          3 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          3 |                        | f                |                  91 | 2025-05-08 11:01:31.722306+00 | fraudsvc      | 2025-05-13 10:35:43.278505+00 | fraudsvc       |          |                     |                             | t
 low_corporate_queue      | Low Corporate Queue      |            | online_fraud_domain | corporate_triage_type  | f                 |                          6 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          6 |                        | f                |                  90 | 2025-05-08 11:06:05.633083+00 | fraudsvc      | 2025-05-13 10:09:13.908608+00 | fraudsvc       |          |                     |                             | t
(6 rows)


    alert_id     | actionable_entity_id | actionable_entity_type_id | actionable_entity_label_nm | parent_entity_id | parent_entity_type_id | contact_entity_id | contact_entity_type_id | score_val | alert_origin_cd |           alert_origin_id            | status_cd | productivity_rating_cd | checkout_user_id | checkout_dttm | checkout_service_type_cd | disposition_dttm | auto_activate_dttm | auto_close_dttm |   auto_close_in_queue_dttm    | opt_lock_version_no |      domain_id      |      queue_id       | alert_type_cd | alert_trigger_txt |                                                                                         enrichment_json_doc                                                                                         |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | disposition_reason_cd
-----------------+----------------------+---------------------------+----------------------------+------------------+-----------------------+-------------------+------------------------+-----------+-----------------+--------------------------------------+-----------+------------------------+------------------+---------------+--------------------------+------------------+--------------------+-----------------+-------------------------------+---------------------+---------------------+---------------------+---------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+---------------+-------------------------------+----------------+-----------------------
 907741815693373 | test05               | sfd_customer              | test05                     | test05           | sfd_customer          | test05            | sfd_customer           |         0 | KAFKA           | f4e9e8b5-7763-4d14-921e-a553b3f7ddb7 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:30:31.902282+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:30:31.903125+00 | sas.alerts    | 2025-05-13 12:30:31.903125+00 | sas.alerts     |
 025629746001441 | test06               | sfd_customer              | test06                     | test06           | sfd_customer          | test06            | sfd_customer           |         0 | KAFKA           | a391052d-8f77-4937-96cc-82a578a0be33 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:38:11.163237+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:38:11.163521+00 | sas.alerts    | 2025-05-13 12:38:11.163521+00 | sas.alerts     |
 858321391877415 | r2_025               | sfd_customer              | r2_025                     | r2_025           | sfd_customer          | r2_025            | sfd_customer           |         0 | KAFKA           | d9e9a7d1-9022-4a7f-973c-7cabbe40c00a | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:23:31.60331+00  |                   2 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:03:39.499401+00 | sas.alerts    | 2025-05-13 13:23:31.608277+00 | sas.alerts     |
 423559934506779 | r2_026               | sfd_customer              | r2_026                     | r2_026           | sfd_customer          | r2_026            | sfd_customer           |         0 | KAFKA           | 3d643206-4ce9-4df1-b2ab-f49a546ee79b | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:23:53.530595+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:23:53.530979+00 | sas.alerts    | 2025-05-13 13:23:53.530979+00 | sas.alerts     |
(4 rows)



    alert_id     | actionable_entity_id | actionable_entity_type_id | actionable_entity_label_nm | parent_entity_id | parent_entity_type_id | contact_entity_id | contact_entity_type_id | score_val | alert_origin_cd |           alert_origin_id            | status_cd | productivity_rating_cd | checkout_user_id | checkout_dttm | checkout_service_type_cd | disposition_dttm | auto_activate_dttm | auto_close_dttm |   auto_close_in_queue_dttm    | opt_lock_version_no |      domain_id      |      queue_id       | alert_type_cd | alert_trigger_txt |                                                                                         enrichment_json_doc                                                                                         |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | disposition_reason_cd
-----------------+----------------------+---------------------------+----------------------------+------------------+-----------------------+-------------------+------------------------+-----------+-----------------+--------------------------------------+-----------+------------------------+------------------+---------------+--------------------------+------------------+--------------------+-----------------+-------------------------------+---------------------+---------------------+---------------------+---------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+---------------+-------------------------------+----------------+-----------------------
 907741815693373 | test05               | sfd_customer              | test05                     | test05           | sfd_customer          | test05            | sfd_customer           |         0 | KAFKA           | f4e9e8b5-7763-4d14-921e-a553b3f7ddb7 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:30:31.902282+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:30:31.903125+00 | sas.alerts    | 2025-05-13 12:30:31.903125+00 | sas.alerts     |
 025629746001441 | test06               | sfd_customer              | test06                     | test06           | sfd_customer          | test06            | sfd_customer           |         0 | KAFKA           | a391052d-8f77-4937-96cc-82a578a0be33 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:38:11.163237+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:38:11.163521+00 | sas.alerts    | 2025-05-13 12:38:11.163521+00 | sas.alerts     |
 858321391877415 | r2_025               | sfd_customer              | r2_025                     | r2_025           | sfd_customer          | r2_025            | sfd_customer           |         0 | KAFKA           | d9e9a7d1-9022-4a7f-973c-7cabbe40c00a | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:23:31.60331+00  |                   2 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:03:39.499401+00 | sas.alerts    | 2025-05-13 13:23:31.608277+00 | sas.alerts     |
 423559934506779 | r2_026               | sfd_customer              | r2_026                     | r2_026           | sfd_customer          | r2_026            | sfd_customer           |         0 | KAFKA           | 3d643206-4ce9-4df1-b2ab-f49a546ee79b | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:23:53.530595+00 |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:23:53.530979+00 | sas.alerts    | 2025-05-13 13:23:53.530979+00 | sas.alerts     |
 460114502155306 | r2_027               | sfd_customer              | r2_027                     | r2_027           | sfd_customer          | r2_027            | sfd_customer           |         0 | KAFKA           | abcc55af-3a2d-43f1-8042-50c77d7a4375 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:30:49.24978+00  |                   1 | online_fraud_domain | low_corporate_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:30:49.250059+00 | sas.alerts    | 2025-05-13 13:30:49.250059+00 | sas.alerts     |
(5 rows)



         queue_id         |         queue_nm         | queue_desc |      domain_id      |     triage_type_id     | default_queue_flg | queue_service_priority_val | queue_service_sort_field_order | queue_service_enabled_flg | alert_max_duration_in_q_val | queue_routing_enabled_flg | queue_routing_priority_val | queue_routing_rule_val | queue_sticky_flg | opt_lock_version_no |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | group_id | auto_disposition_id | queue_reactivation_rule_val | queue_reactivation_enabled_flg
--------------------------+--------------------------+------------+---------------------+------------------------+-------------------+----------------------------+--------------------------------+---------------------------+-----------------------------+---------------------------+----------------------------+------------------------+------------------+---------------------+-------------------------------+---------------+-------------------------------+----------------+----------+---------------------+-----------------------------+--------------------------------
 low_individual_queue     | Low Individual Queue     |            | online_fraud_domain | individual_triage_type | f                 |                          3 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          3 |                        | f                |                  91 | 2025-05-08 11:01:31.722306+00 | fraudsvc      | 2025-05-13 10:35:43.278505+00 | fraudsvc       |          |                     |                             | t
 high_corporate_queue     | High Corporate Queue     |            | online_fraud_domain | corporate_triage_type  | f                 |                          5 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          5 |                        | f                |                  90 | 2025-05-08 11:06:05.619586+00 | fraudsvc      | 2025-05-13 10:09:13.889841+00 | fraudsvc       |          |                     |                             | t
 high_individual_queue    | High Individual Queue    |            | online_fraud_domain | individual_triage_type | f                 |                          2 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          2 |                        | f                |                  90 | 2025-05-08 11:01:31.695844+00 | fraudsvc      | 2025-05-13 10:09:13.899229+00 | fraudsvc       |          |                     |                             | t
 manager_corporate_queue  | Manager Corporate Queue  |            | online_fraud_domain | corporate_triage_type  | f                 |                          4 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          4 |                        | f                |                  90 | 2025-05-08 11:06:05.645544+00 | fraudsvc      | 2025-05-13 10:09:13.927335+00 | fraudsvc       |          |                     |                             | t
 manager_individual_queue | Manager Individual Queue |            | online_fraud_domain | individual_triage_type | f                 |                          1 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          1 |                        | f                |                  90 | 2025-05-08 11:01:31.738083+00 | fraudsvc      | 2025-05-13 10:09:13.936805+00 | fraudsvc       |          |                     |                             | t
 low_corporate_queue      | Low Corporate Queue      |            | online_fraud_domain | corporate_triage_type  | f                 |                        100 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                        100 |                        | f                |                  91 | 2025-05-08 11:06:05.633083+00 | fraudsvc      | 2025-05-13 13:23:21.065464+00 | fraudsvc       |          |                     |                             | t
(6 rows)







         queue_id         |         queue_nm         | queue_desc |      domain_id      |     triage_type_id     | default_queue_flg | queue_service_priority_val | queue_service_sort_field_order | queue_service_enabled_flg | alert_max_duration_in_q_val | queue_routing_enabled_flg | queue_routing_priority_val | queue_routing_rule_val | queue_sticky_flg | opt_lock_version_no |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | group_id | auto_disposition_id | queue_reactivation_rule_val | queue_reactivation_enabled_flg
--------------------------+--------------------------+------------+---------------------+------------------------+-------------------+----------------------------+--------------------------------+---------------------------+-----------------------------+---------------------------+----------------------------+------------------------+------------------+---------------------+-------------------------------+---------------+-------------------------------+----------------+----------+---------------------+-----------------------------+--------------------------------
 low_individual_queue     | Low Individual Queue     |            | online_fraud_domain | individual_triage_type | f                 |                          3 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                        101 |                        | f                |                  91 | 2025-05-08 11:01:31.722306+00 | fraudsvc      | 2025-05-13 10:35:43.278505+00 | fraudsvc       |          |                     |                             | t
 high_corporate_queue     | High Corporate Queue     |            | online_fraud_domain | corporate_triage_type  | f                 |                          5 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          5 |                        | f                |                  90 | 2025-05-08 11:06:05.619586+00 | fraudsvc      | 2025-05-13 10:09:13.889841+00 | fraudsvc       |          |                     |                             | t
 high_individual_queue    | High Individual Queue    |            | online_fraud_domain | individual_triage_type | f                 |                          2 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          2 |                        | f                |                  90 | 2025-05-08 11:01:31.695844+00 | fraudsvc      | 2025-05-13 10:09:13.899229+00 | fraudsvc       |          |                     |                             | t
 manager_corporate_queue  | Manager Corporate Queue  |            | online_fraud_domain | corporate_triage_type  | f                 |                          4 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          4 |                        | f                |                  90 | 2025-05-08 11:06:05.645544+00 | fraudsvc      | 2025-05-13 10:09:13.927335+00 | fraudsvc       |          |                     |                             | t
 manager_individual_queue | Manager Individual Queue |            | online_fraud_domain | individual_triage_type | f                 |                          1 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          1 |                        | f                |                  90 | 2025-05-08 11:01:31.738083+00 | fraudsvc      | 2025-05-13 10:09:13.936805+00 | fraudsvc       |          |                     |                             | t
 low_corporate_queue      | Low Corporate Queue      |            | online_fraud_domain | corporate_triage_type  | f                 |                        100 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                        100 |                        | f                |                  91 | 2025-05-08 11:06:05.633083+00 | fraudsvc      | 2025-05-13 13:23:21.065464+00 | fraudsvc       |          |                     |                             | t
(6 rows)







         queue_id         |         queue_nm         | queue_desc |      domain_id      |     triage_type_id     | default_queue_flg | queue_service_priority_val | queue_service_sort_field_order | queue_service_enabled_flg | alert_max_duration_in_q_val | queue_routing_enabled_flg | queue_routing_priority_val | queue_routing_rule_val | queue_sticky_flg | opt_lock_version_no |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | group_id | auto_disposition_id | queue_reactivation_rule_val | queue_reactivation_enabled_flg
--------------------------+--------------------------+------------+---------------------+------------------------+-------------------+----------------------------+--------------------------------+---------------------------+-----------------------------+---------------------------+----------------------------+------------------------+------------------+---------------------+-------------------------------+---------------+-------------------------------+----------------+----------+---------------------+-----------------------------+--------------------------------
 low_individual_queue     | Low Individual Queue     |            | online_fraud_domain | individual_triage_type | f                 |                          3 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                        101 |                        | f                |                  91 | 2025-05-08 11:01:31.722306+00 | fraudsvc      | 2025-05-13 10:35:43.278505+00 | fraudsvc       |          |                     |                             | t
 high_corporate_queue     | High Corporate Queue     |            | online_fraud_domain | corporate_triage_type  | f                 |                          5 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          5 |                        | f                |                  90 | 2025-05-08 11:06:05.619586+00 | fraudsvc      | 2025-05-13 10:09:13.889841+00 | fraudsvc       |          |                     |                             | t
 high_individual_queue    | High Individual Queue    |            | online_fraud_domain | individual_triage_type | f                 |                          2 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          2 |                        | f                |                  90 | 2025-05-08 11:01:31.695844+00 | fraudsvc      | 2025-05-13 10:09:13.899229+00 | fraudsvc       |          |                     |                             | t
 manager_corporate_queue  | Manager Corporate Queue  |            | online_fraud_domain | corporate_triage_type  | f                 |                          4 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          4 |                        | f                |                  90 | 2025-05-08 11:06:05.645544+00 | fraudsvc      | 2025-05-13 10:09:13.927335+00 | fraudsvc       |          |                     |                             | t
 manager_individual_queue | Manager Individual Queue |            | online_fraud_domain | individual_triage_type | f                 |                          1 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                          1 |                        | f                |                  90 | 2025-05-08 11:01:31.738083+00 | fraudsvc      | 2025-05-13 10:09:13.936805+00 | fraudsvc       |          |                     |                             | t
 low_corporate_queue      | Low Corporate Queue      |            | online_fraud_domain | corporate_triage_type  | f                 |                        100 | creationTimeStamp:ascending    | t                         |                        8760 | t                         |                        100 |                        | f                |                  91 | 2025-05-08 11:06:05.633083+00 | fraudsvc      | 2025-05-13 13:23:21.065464+00 | fraudsvc       |          |                     |                             | t
(6 rows)

m    | opt_lock_version_no |      domain_id      |       queue_id       | alert_type_cd | alert_trigger_txt |                                                                                         enrichment_json_doc                                                                                         |         creation_dttm         | created_by_nm |         modified_dttm         | modified_by_nm | disposition_reason_cd
-----------------+----------------------+---------------------------+----------------------------+------------------+-----------------------+-------------------+------------------------+-----------+-----------------+--------------------------------------+-----------+------------------------+------------------+---------------+--------------------------+------------------+--------------------+-----------------+-------------------------------+---------------------+---------------------+----------------------+---------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+---------------+-------------------------------+----------------+-----------------------
 907741815693373 | test05               | sfd_customer              | test05                     | test05           | sfd_customer          | test05            | sfd_customer           |         0 | KAFKA           | f4e9e8b5-7763-4d14-921e-a553b3f7ddb7 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:30:31.902282+00 |                   1 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:30:31.903125+00 | sas.alerts    | 2025-05-13 12:30:31.903125+00 | sas.alerts     |
 025629746001441 | test06               | sfd_customer              | test06                     | test06           | sfd_customer          | test06            | sfd_customer           |         0 | KAFKA           | a391052d-8f77-4937-96cc-82a578a0be33 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:38:11.163237+00 |                   1 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:38:11.163521+00 | sas.alerts    | 2025-05-13 12:38:11.163521+00 | sas.alerts     |
 858321391877415 | r2_025               | sfd_customer              | r2_025                     | r2_025           | sfd_customer          | r2_025            | sfd_customer           |         0 | KAFKA           | d9e9a7d1-9022-4a7f-973c-7cabbe40c00a | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:23:31.60331+00  |                   2 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:03:39.499401+00 | sas.alerts    | 2025-05-13 13:23:31.608277+00 | sas.alerts     |
 423559934506779 | r2_026               | sfd_customer              | r2_026                     | r2_026           | sfd_customer          | r2_026            | sfd_customer           |         0 | KAFKA           | 3d643206-4ce9-4df1-b2ab-f49a546ee79b | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:23:53.530595+00 |                   1 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:23:53.530979+00 | sas.alerts    | 2025-05-13 13:23:53.530979+00 | sas.alerts     |
 460114502155306 | r2_027               | sfd_customer              | r2_027                     | r2_027           | sfd_customer          | r2_027            | sfd_customer           |         0 | KAFKA           | abcc55af-3a2d-43f1-8042-50c77d7a4375 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:30:49.24978+00  |                   1 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:30:49.250059+00 | sas.alerts    | 2025-05-13 13:30:49.250059+00 | sas.alerts     |
 777165087302929 | r2_028               | sfd_customer              | r2_028                     | r2_028           | sfd_customer          | r2_028            | sfd_customer           |         0 | KAFKA           | 024247eb-c997-4204-9371-766c31459188 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:36:22.219407+00 |                   1 | online_fraud_domain | low_individual_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:36:22.219693+00 | sas.alerts    | 2025-05-13 13:36:22.219693+00 | sas.alerts     |
(6 rows)

(END)


-----+---------------------+---------------------+----------------------+---------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+---------------+-------------------------------+----------------+-----------------------
 907741815693373 | test05               | sfd_customer              | test05                     | test05           | sfd_customer          | test05            | sfd_customer           |         0 | KAFKA           | f4e9e8b5-7763-4d14-921e-a553b3f7ddb7 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:30:31.902282+00 |                   1 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:30:31.903125+00 | sas.alerts    | 2025-05-13 12:30:31.903125+00 | sas.alerts     |
 025629746001441 | test06               | sfd_customer              | test06                     | test06           | sfd_customer          | test06            | sfd_customer           |         0 | KAFKA           | a391052d-8f77-4937-96cc-82a578a0be33 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 12:38:11.163237+00 |                   1 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CK", "sfd_sol_activityType_enrch": "PT", "sfd_sol_customerType_enrch": "PE"} | 2025-05-13 12:38:11.163521+00 | sas.alerts    | 2025-05-13 12:38:11.163521+00 | sas.alerts     |
 858321391877415 | r2_025               | sfd_customer              | r2_025                     | r2_025           | sfd_customer          | r2_025            | sfd_customer           |         0 | KAFKA           | d9e9a7d1-9022-4a7f-973c-7cabbe40c00a | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:23:31.60331+00  |                   2 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:03:39.499401+00 | sas.alerts    | 2025-05-13 13:23:31.608277+00 | sas.alerts     |
 423559934506779 | r2_026               | sfd_customer              | r2_026                     | r2_026           | sfd_customer          | r2_026            | sfd_customer           |         0 | KAFKA           | 3d643206-4ce9-4df1-b2ab-f49a546ee79b | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:23:53.530595+00 |                   1 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:23:53.530979+00 | sas.alerts    | 2025-05-13 13:23:53.530979+00 | sas.alerts     |
 460114502155306 | r2_027               | sfd_customer              | r2_027                     | r2_027           | sfd_customer          | r2_027            | sfd_customer           |         0 | KAFKA           | abcc55af-3a2d-43f1-8042-50c77d7a4375 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:30:49.24978+00  |                   1 | online_fraud_domain | low_corporate_queue  | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:30:49.250059+00 | sas.alerts    | 2025-05-13 13:30:49.250059+00 | sas.alerts     |
 777165087302929 | r2_028               | sfd_customer              | r2_028                     | r2_028           | sfd_customer          | r2_028            | sfd_customer           |         0 | KAFKA           | 024247eb-c997-4204-9371-766c31459188 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 13:36:22.219407+00 |                   1 | online_fraud_domain | low_individual_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 13:36:22.219693+00 | sas.alerts    | 2025-05-13 13:36:22.219693+00 | sas.alerts     |
 152953806683247 | r2_029               | sfd_customer              | r2_029                     | r2_029           | sfd_customer          | r2_029            | sfd_customer           |         0 | KAFKA           | d5d586f4-66de-46df-9677-4186da196704 | ACTIVE    |                        |                  |               |                          |                  |                    |                 | 2026-05-13 14:15:29.633112+00 |                   1 | online_fraud_domain | low_individual_queue | sfd_customer  |                   | {"sfd_dec_outcome_enrch": 0, "sfd_sol_chnType_enrch": "DM", "sfd_sol_authType_enrch": "NA", "sfd_sol_origType_enrch": "CS", "sfd_sol_activityType_enrch": "NM", "sfd_sol_customerType_enrch": "BU"} | 2025-05-13 14:15:29.633454+00 | sas.alerts    | 2025-05-13 14:15:29.633454+00 | sas.alerts     |



